spring:
  profiles:
    include: dev, secrets

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/zhcet?useSSL=false
    username: zhcetuser
    password: zhcetpass

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    mode: HTML5


server:
  http2:
    enabled: true
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  undertow:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

logging:
  file: logs/spring.log

# Please don't add any secrets here, create a new file application-secrets.yaml and override these settings there
# Or see application-dev.yaml or application-prod.yaml and add development or production related settings in
# application-secrets-dev.yaml / application-secrets.prod.yaml
#
# Obviously, you can override any of these settings using any other Spring Profiles method
# This area only defines default properties and documents all possible secret configurations
#
# These will be automatically overridden from values in application-secrets-(dev/prod) according to the active profile
zhcet:
  email:
    disabled: true
  firebase:
    disabled: true
  security:
    pepper: some_nice_pepper
    roles:
      hierarchy:
        ROLE_DEVELOPMENT_SUPER_ADMIN: ROLE_SUPER_ADMIN, ROLE_DEVELOPMENT_ADMIN
        ROLE_SUPER_ADMIN: ROLE_DEAN_ADMIN, ROLE_SUPER_FACULTY, ROLE_DEPARTMENT_SUPER_ADMIN
        ROLE_SUPER_FACULTY: ROLE_FACULTY
        ROLE_DEPARTMENT_SUPER_ADMIN: ROLE_DEPARTMENT_ADMIN
        ROLE_DEAN_ADMIN: ROLE_TEACHING_STAFF
        ROLE_DEPARTMENT_ADMIN: ROLE_TEACHING_STAFF
        ROLE_FACULTY: ROLE_TEACHING_STAFF
