spring:
  profiles:
    include: dev, secrets

  jpa:
    # TODO: Provide better solution for lazy loading
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/zhcet
    username: zhcet
    password: zhcetpass

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 8000
          connectiontimeout: 10000
          writetimeout: 10000
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized

server:
  http2:
    enabled: true
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
  undertow:
    accesslog:
      enabled: true
      pattern: '%t %l %h %u "%r" %s %b "%{i,Referer}" "%{i,User-Agent}" (%D ms)'
      dir: "${zhcet.storage.root-dir}/logs/access"
  servlet:
    session:
      cookie:
        http-only: true
        name: ZHCET_SESSION_ID

logging:
  file: "${zhcet.storage.root-dir}/logs/spring.log"
  path: "${zhcet.storage.root-dir}/logs"
  level:
    root: INFO
    amu.zhcet: TRACE

# Please don't add any secrets here, create a new file application-secrets.yaml and override these settings there
# Or see application-dev.yaml or application-prod.yaml and add development or production related settings in
# application-secrets-dev.yaml / application-secrets.prod.yaml
#
# Obviously, you can override any of these settings using any other Spring Profiles method
# This area only defines default properties and documents all possible secret configurations
#
# These will be automatically overridden from values in application-secrets-(dev/prod) according to the active profile
zhcet:
  email:
    disabled: true
  firebase:
    disabled: true
  storage:
    root-dir: app-root
  security:
    pepper: some_nice_pepper
    roles:
      hierarchy:
        ROLE_DEVELOPMENT_SUPER_ADMIN: ROLE_SUPER_ADMIN, ROLE_DEVELOPMENT_ADMIN
        ROLE_DEVELOPMENT_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_DEAN_ADMIN, ROLE_SUPER_FACULTY, ROLE_DEPARTMENT_SUPER_ADMIN
        ROLE_SUPER_FACULTY: ROLE_FACULTY
        ROLE_DEPARTMENT_SUPER_ADMIN: ROLE_DEPARTMENT_ADMIN
        ROLE_DEAN_ADMIN: ROLE_TEACHING_STAFF
        ROLE_DEPARTMENT_ADMIN: ROLE_TEACHING_STAFF
        ROLE_FACULTY: ROLE_TEACHING_STAFF
        ROLE_TEACHING_STAFF: ROLE_USER, ROLE_VERIFIED_USER
        ROLE_STUDENT: ROLE_USER, ROLE_VERIFIED_USER
